# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-23 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tix_app', '0006_auto_20180523_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_name',
        ),
    ]
