# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-23 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tix_app', '0007_remove_photo_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='receipt_file',
            field=models.FileField(default='', upload_to='/receipt'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.FileField(upload_to=''),
        ),
    ]
