# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tix_app', '0008_auto_20180523_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.FileField(upload_to='ticket_photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='receipt_file',
            field=models.FileField(default='', upload_to='receipt'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sell_score',
            field=models.IntegerField(choices=[(0, 'average'), (1, 'good'), (2, 'great')], default=0),
        ),
    ]
