# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tix_app', '0009_auto_20180524_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.FileField(default='', upload_to='ticket_photo'),
        ),
    ]
